// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Alert is the predicate function for alert builders.
type Alert func(*sql.Selector)

// RoleBinding is the predicate function for rolebinding builders.
type RoleBinding func(*sql.Selector)

// Server is the predicate function for server builders.
type Server func(*sql.Selector)

// ServiceTree is the predicate function for servicetree builders.
type ServiceTree func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
