// Code generated by entc, DO NOT EDIT.

package server

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the server type in the database.
	Label = "server"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldMachineType holds the string denoting the machine_type field in the database.
	FieldMachineType = "machine_type"
	// FieldPlatformType holds the string denoting the platform_type field in the database.
	FieldPlatformType = "platform_type"
	// FieldSystemType holds the string denoting the system_type field in the database.
	FieldSystemType = "system_type"
	// Table holds the table name of the server in the database.
	Table = "servers"
)

// Columns holds all SQL columns for server fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldIP,
	FieldMachineType,
	FieldPlatformType,
	FieldSystemType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)

// MachineType defines the type for the "machine_type" enum field.
type MachineType string

// MachineType values.
const (
	MachineTypePhysical MachineType = "physical"
	MachineTypeVirtual  MachineType = "virtual"
)

func (mt MachineType) String() string {
	return string(mt)
}

// MachineTypeValidator is a validator for the "machine_type" field enum values. It is called by the builders before save.
func MachineTypeValidator(mt MachineType) error {
	switch mt {
	case MachineTypePhysical, MachineTypeVirtual:
		return nil
	default:
		return fmt.Errorf("server: invalid enum value for machine_type field: %q", mt)
	}
}

// PlatformType defines the type for the "platform_type" enum field.
type PlatformType string

// PlatformType values.
const (
	PlatformTypeZstack    PlatformType = "zstack"
	PlatformTypeK8s       PlatformType = "k8s"
	PlatformTypeOpenstack PlatformType = "openstack"
)

func (pt PlatformType) String() string {
	return string(pt)
}

// PlatformTypeValidator is a validator for the "platform_type" field enum values. It is called by the builders before save.
func PlatformTypeValidator(pt PlatformType) error {
	switch pt {
	case PlatformTypeZstack, PlatformTypeK8s, PlatformTypeOpenstack:
		return nil
	default:
		return fmt.Errorf("server: invalid enum value for platform_type field: %q", pt)
	}
}

// SystemType defines the type for the "system_type" enum field.
type SystemType string

// SystemType values.
const (
	SystemTypeLinux   SystemType = "linux"
	SystemTypeWindows SystemType = "windows"
)

func (st SystemType) String() string {
	return string(st)
}

// SystemTypeValidator is a validator for the "system_type" field enum values. It is called by the builders before save.
func SystemTypeValidator(st SystemType) error {
	switch st {
	case SystemTypeLinux, SystemTypeWindows:
		return nil
	default:
		return fmt.Errorf("server: invalid enum value for system_type field: %q", st)
	}
}
