// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cmdb/ent/rolebinding"
	"cmdb/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	rolebindingFields := schema.RoleBinding{}.Fields()
	_ = rolebindingFields
	// rolebindingDescCreatedAt is the schema descriptor for created_at field.
	rolebindingDescCreatedAt := rolebindingFields[3].Descriptor()
	// rolebinding.DefaultCreatedAt holds the default value on creation for the created_at field.
	rolebinding.DefaultCreatedAt = rolebindingDescCreatedAt.Default.(func() time.Time)
}
