// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cmdb/ent/rolebinding"
	"cmdb/ent/schema"
	"cmdb/ent/server"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	rolebindingMixin := schema.RoleBinding{}.Mixin()
	rolebindingMixinFields0 := rolebindingMixin[0].Fields()
	_ = rolebindingMixinFields0
	rolebindingFields := schema.RoleBinding{}.Fields()
	_ = rolebindingFields
	// rolebindingDescCreateTime is the schema descriptor for create_time field.
	rolebindingDescCreateTime := rolebindingMixinFields0[0].Descriptor()
	// rolebinding.DefaultCreateTime holds the default value on creation for the create_time field.
	rolebinding.DefaultCreateTime = rolebindingDescCreateTime.Default.(func() time.Time)
	// rolebindingDescUpdateTime is the schema descriptor for update_time field.
	rolebindingDescUpdateTime := rolebindingMixinFields0[1].Descriptor()
	// rolebinding.DefaultUpdateTime holds the default value on creation for the update_time field.
	rolebinding.DefaultUpdateTime = rolebindingDescUpdateTime.Default.(func() time.Time)
	// rolebinding.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	rolebinding.UpdateDefaultUpdateTime = rolebindingDescUpdateTime.UpdateDefault.(func() time.Time)
	serverMixin := schema.Server{}.Mixin()
	serverMixinFields0 := serverMixin[0].Fields()
	_ = serverMixinFields0
	serverFields := schema.Server{}.Fields()
	_ = serverFields
	// serverDescCreateTime is the schema descriptor for create_time field.
	serverDescCreateTime := serverMixinFields0[0].Descriptor()
	// server.DefaultCreateTime holds the default value on creation for the create_time field.
	server.DefaultCreateTime = serverDescCreateTime.Default.(func() time.Time)
	// serverDescUpdateTime is the schema descriptor for update_time field.
	serverDescUpdateTime := serverMixinFields0[1].Descriptor()
	// server.DefaultUpdateTime holds the default value on creation for the update_time field.
	server.DefaultUpdateTime = serverDescUpdateTime.Default.(func() time.Time)
	// server.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	server.UpdateDefaultUpdateTime = serverDescUpdateTime.UpdateDefault.(func() time.Time)
}
