// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cmdb/ent/server"
	"cmdb/ent/servicetree"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceTreeCreate is the builder for creating a ServiceTree entity.
type ServiceTreeCreate struct {
	config
	mutation *ServiceTreeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (stc *ServiceTreeCreate) SetName(s string) *ServiceTreeCreate {
	stc.mutation.SetName(s)
	return stc
}

// SetNote sets the "note" field.
func (stc *ServiceTreeCreate) SetNote(s string) *ServiceTreeCreate {
	stc.mutation.SetNote(s)
	return stc
}

// SetType sets the "type" field.
func (stc *ServiceTreeCreate) SetType(s servicetree.Type) *ServiceTreeCreate {
	stc.mutation.SetType(s)
	return stc
}

// SetProjectID sets the "project" edge to the ServiceTree entity by ID.
func (stc *ServiceTreeCreate) SetProjectID(id int) *ServiceTreeCreate {
	stc.mutation.SetProjectID(id)
	return stc
}

// SetNillableProjectID sets the "project" edge to the ServiceTree entity by ID if the given value is not nil.
func (stc *ServiceTreeCreate) SetNillableProjectID(id *int) *ServiceTreeCreate {
	if id != nil {
		stc = stc.SetProjectID(*id)
	}
	return stc
}

// SetProject sets the "project" edge to the ServiceTree entity.
func (stc *ServiceTreeCreate) SetProject(s *ServiceTree) *ServiceTreeCreate {
	return stc.SetProjectID(s.ID)
}

// AddServiceIDs adds the "service" edge to the ServiceTree entity by IDs.
func (stc *ServiceTreeCreate) AddServiceIDs(ids ...int) *ServiceTreeCreate {
	stc.mutation.AddServiceIDs(ids...)
	return stc
}

// AddService adds the "service" edges to the ServiceTree entity.
func (stc *ServiceTreeCreate) AddService(s ...*ServiceTree) *ServiceTreeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return stc.AddServiceIDs(ids...)
}

// AddServerIDs adds the "servers" edge to the Server entity by IDs.
func (stc *ServiceTreeCreate) AddServerIDs(ids ...int) *ServiceTreeCreate {
	stc.mutation.AddServerIDs(ids...)
	return stc
}

// AddServers adds the "servers" edges to the Server entity.
func (stc *ServiceTreeCreate) AddServers(s ...*Server) *ServiceTreeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return stc.AddServerIDs(ids...)
}

// Mutation returns the ServiceTreeMutation object of the builder.
func (stc *ServiceTreeCreate) Mutation() *ServiceTreeMutation {
	return stc.mutation
}

// Save creates the ServiceTree in the database.
func (stc *ServiceTreeCreate) Save(ctx context.Context) (*ServiceTree, error) {
	var (
		err  error
		node *ServiceTree
	)
	if len(stc.hooks) == 0 {
		if err = stc.check(); err != nil {
			return nil, err
		}
		node, err = stc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServiceTreeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = stc.check(); err != nil {
				return nil, err
			}
			stc.mutation = mutation
			if node, err = stc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(stc.hooks) - 1; i >= 0; i-- {
			if stc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = stc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, stc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (stc *ServiceTreeCreate) SaveX(ctx context.Context) *ServiceTree {
	v, err := stc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (stc *ServiceTreeCreate) Exec(ctx context.Context) error {
	_, err := stc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stc *ServiceTreeCreate) ExecX(ctx context.Context) {
	if err := stc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (stc *ServiceTreeCreate) check() error {
	if _, ok := stc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	if _, ok := stc.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "note"`)}
	}
	if _, ok := stc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "type"`)}
	}
	if v, ok := stc.mutation.GetType(); ok {
		if err := servicetree.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "type": %w`, err)}
		}
	}
	return nil
}

func (stc *ServiceTreeCreate) sqlSave(ctx context.Context) (*ServiceTree, error) {
	_node, _spec := stc.createSpec()
	if err := sqlgraph.CreateNode(ctx, stc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (stc *ServiceTreeCreate) createSpec() (*ServiceTree, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceTree{config: stc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: servicetree.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: servicetree.FieldID,
			},
		}
	)
	if value, ok := stc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: servicetree.FieldName,
		})
		_node.Name = value
	}
	if value, ok := stc.mutation.Note(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: servicetree.FieldNote,
		})
		_node.Note = value
	}
	if value, ok := stc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: servicetree.FieldType,
		})
		_node.Type = value
	}
	if nodes := stc.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servicetree.ProjectTable,
			Columns: []string{servicetree.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: servicetree.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.service_tree_service = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := stc.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicetree.ServiceTable,
			Columns: []string{servicetree.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: servicetree.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := stc.mutation.ServersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   servicetree.ServersTable,
			Columns: []string{servicetree.ServersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: server.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ServiceTreeCreateBulk is the builder for creating many ServiceTree entities in bulk.
type ServiceTreeCreateBulk struct {
	config
	builders []*ServiceTreeCreate
}

// Save creates the ServiceTree entities in the database.
func (stcb *ServiceTreeCreateBulk) Save(ctx context.Context) ([]*ServiceTree, error) {
	specs := make([]*sqlgraph.CreateSpec, len(stcb.builders))
	nodes := make([]*ServiceTree, len(stcb.builders))
	mutators := make([]Mutator, len(stcb.builders))
	for i := range stcb.builders {
		func(i int, root context.Context) {
			builder := stcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceTreeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, stcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, stcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, stcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (stcb *ServiceTreeCreateBulk) SaveX(ctx context.Context) []*ServiceTree {
	v, err := stcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (stcb *ServiceTreeCreateBulk) Exec(ctx context.Context) error {
	_, err := stcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stcb *ServiceTreeCreateBulk) ExecX(ctx context.Context) {
	if err := stcb.Exec(ctx); err != nil {
		panic(err)
	}
}
